name: Trigger Website Build

on:
  push:
    branches:
      - main

jobs:
  ping-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send signal to main repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SYNC_TOKEN }} \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/davpsasnl/davpsasnl.github.io/dpatches \
          -d '{"event_type": "content_updated"}'
